services:
  traefik:
    container_name: traefik
    image: traefik:latest
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=homelab-network
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --providers.file.directory=/etc/traefik
      - --providers.file.watch=true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/shared/portainer/traefik/config:/etc/traefik:ro
    networks:
      - homelab-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.koye.casa`)"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.service=api@internal"
    restart: unless-stopped

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "7070:80/tcp"
      - "7443:443/tcp"
    environment:
      TZ: 'Europe/Warsaw'
      FTLCONF_dns_upstreams: '1.1.1.1;8.8.8.8'
      FTLCONF_webserver_api_password: ''
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      - /mnt/shared/portainer/pihole/pihole:/etc/pihole
      - /mnt/shared/portainer/pihole/dnsmasq:/etc/dnsmasq.d
    networks:
      - homelab-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.koye.casa`)"
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
    restart: unless-stopped

networks:
  homelab-network:
    name: homelab-network
    driver: bridge