services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    environment:
      - TZ=Europe/Warsaw
      - JELLYFIN_PublishedServerUrl=https://jellyfin.home
    volumes:
      - /mnt/shared/portainer/jellyfin/config:/config
      - /mnt/shared/portainer/jellyfin/cache:/cache
      - /mnt/shared/media:/media:ro
    ports:
      - "7359:7359/udp" # Auto-discovery
      - "1900:1900/udp" # DLNA
    networks:
      - homelab-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.home`)"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri # Hardware acceleration (if available)

networks:
  homelab-network:
    name: homelab-network
    external: true