- name: Homelab
  columns:
    - size: full
      widgets:
        - type: bookmarks
          title: Services
          groups:
            - title: Infra
              color: 200 50 50
              links:
                - title: Beszel
                  url: https://monitor.koye.casa
                  description: System Monitoring
                  icon: si:grafana
                - title: Glance
                  url: https://app.koye.casa
                  description: Dashboard Hub
                  icon: si:glance
                - title: Pi-hole
                  url: https://pihole.koye.casa/admin
                  description: DNS & Ad Blocker
                  icon: si:pihole
                - title: Traefik
                  url: https://traefik.koye.casa
                  description: Reverse Proxy Dashboard
                  icon: si:traefik

            - title: Media
              color: 300 50 50
              links:
                - title: Audible
                  url: https://audible.koye.casa
                  description: Audiobook Library
                  icon: si:audiobookshelf
                - title: Jellyfin
                  url: https://jellyfin.koye.casa
                  description: Media Server
                  icon: si:jellyfin

            - title: Tools
              color: 60 50 50
              links:
                - title: Books
                  url: https://books.koye.casa
                  description: E-book Library & Management
                  icon: di:calibre
                - title: Chat
                  url: https://chat.koye.casa
                  description: AI Chat Interface
                  icon: si:openai
                - title: Kavita
                  url: https://kavita.koye.casa
                  description: Media Server
                  icon: di:kavita
                - title: SaveBooks
                  url: https://savebooks.koye.casa
                  description: Automated Book Downloader
                  icon: di:vault
                
        - type: docker-containers
          title: Docker Containers
          hide-by-default: false